# Run tests in Stata zomg

name: tests
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches: [ master ]
jobs:
  build:
    name: Run Tests in Stata
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Stata Docker
        run: |
          echo "============ Setup ============"
          echo ${STATA_LIC_17} > stata.lic
          shasum stata.lic
          ls -laht stata.lic
          rm -f src/tests/tests_unix.log
          chmod a+rwX src src/tests
          echo "============ Downloadng Docker ============"
          export VERSION=17
          export TAG=2023-01-10
          export MYHUBID=dataeditors
          export MYIMG=stata${VERSION}
          export STATALIC=$(pwd)/stata.lic
          docker pull dataeditors/stata17:2023-01-10
          echo "============ Running Tests ============"
          docker run --rm -v ${STATALIC}:/usr/local/stata/stata.lic -v $(pwd):/shasum ${MYHUBID}/${MYIMG}:${TAG} -b /shasum/src/tests.do
          echo "============ Check Run ============"
          cat src/tests/tests_unix.log
          echo "============ Cleaning License ============"
          rm -f stata.lic
          echo "============ Committing Changes ============"
          echo ${GITHUB_REF##*/}
          [ -n "$(git status --porcelain)" ] && git commit -a -m "[Automated Commit] log file docker run"
          git fetch
          git push -f origin HEAD:${GITHUB_REF##*/}
    env:
      STATA_LIC_17: ${{ secrets.STATA_LIC_17 }}
